# lib/tasks/sass.rake
namespace :sass do
  desc 'Updates stylesheets if necessary from their Sass templates.'
  task :update => :environment do
    Sass::Plugin.update_stylesheets
  end
end

# # config/deploy.rb
# namespace :sass do
#   desc 'Updates the stylesheets generated by Sass'
#   task :update, :roles => :app do
#     run "cd #{latest_release}; RAILS_ENV=#{rails_env} #{rake} sass:update"
#   end
#   before 'deploy:restart', 'sass:update'
# end
